### ISSUE TITLE
[BUG] Remove quote not working in Firefox

### ISSUE THREAD

**Issue by pretor** [sibiraj-s/ngx-editor#161]
# I'm submitting a 

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

In firefox, remove quote is not working.

### Version Information

```
ngx-editor: 3.3.0
angular: 6.1.4
```

### Browser

- [ ] Chrome - x.x.x
- [x]  Mozilla Firefox - 62.0
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by sibiraj-s** [comment]
Will look into it.

**Comment by laimutisign** [comment]
I found, that 'Remove Blockquote' calls 'formatBlock' command, to wrap 'div' element around the text. But in Firefox 63.0 'div' element is placed inside 'blockquote' element instead of removing it. Probably because of the second Boolean parameter with the value 'false' of document.execCommand is not supported in Mozilla:
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Commands

'indent' / 'outdent' commands are working in Firefox 63.0 same as 'Blockquote' and 'Remove Blockquote' supposed to work, so 'outdent' command can be called instead of 'formatBlock' command.

Currently, I had removed editor commands 'Blockquote' and 'Remove Blockquote' for displaying in Firefox, as they duplicate commands 'Indent' and 'Outdent'.
In Chrome 'Indent' and 'Outdent' works differently than 'Blockquote' and 'Remove Blockquote'.
