### ISSUE TITLE
`[BUG]: ERROR in ./node_modules/ngx-editor/fesm2015/ngx-editor.js thrown on macOS`

### ISSUE THREAD

**Issue by gagandeep-s** [sibiraj-s/ngx-editor#246]
ERROR in ./node_modules/ngx-editor/fesm2015/ngx-editor.js
Module not found: Error: Can't resolve 'ngx-bootstrap' in '/node_modules/ngx-editor/fesm2015'

**Comment by sibiraj-s** [comment]
Some information in the issue template is required. At-least it is required to fill in the basic details like angular version, lib version.

There is no enough details in the given description. 

but guessing from the issue. You might be using v4. In v4 you must install peerDependencies yourself.

```bash
npm i ngx-bootstrap
npm i font-awesome
```

 check here for information https://github.com/sibiraj-s/ngx-editor/tree/v4.1.0. 

Closing the issue due to lack of details. please reopen (with enough information) if the above information didn't solve the issue
