### ISSUE TITLE
[feature]: view/edit plain html code

### ISSUE THREAD

**Issue by m-o-t-u** [Sibiraj-S/ngx-editor#26]
Hello

I really like your editor and i'd like to make a suggestion for a new feature: 

It sometimes would be very useful when you can switch to a "plain-html-code-view" where you can edit directly the html code (e.g. add a target="_blank" in a a-tag or something like that).

Can you imagine to add this feature?

Cheers
Martin

**Comment by Sibiraj-S** [comment]
> e.g. add a target="_blank" in a a-tag

Actually, I already have all this feature in mind. I was little tied up. So I was unable to complete that. What I actually planned is to give a select box to toggle `_blank` option while entering the URL.

The other one. Edit HTML was a nice one. but Instead of editing HTML's. It would be nice to give an option to Insert HTML(not edit) because sometimes the user might break the code while editing. In Angular HTML's are strictly validated.

**Comment by idealser** [comment]
Is this feature working in 3.3.0 version? Is it possible to edit plain HTML inside editor?

**Comment by kolkov** [comment]
There is no such function in this editor, but it certainly is in other editors for Angular.

**Comment by VanTigranyan** [comment]
> There is no such function in this editor, but it certainly is in other editors for Angular.

Can you suggest such an editor for angular 6. I am searching for it already for 2 days. There is no editor which have all the functions I need. There is one which is Froala, but its not open source.
