### ISSUE TITLE
[Feature] Set Menu Popup Direction

### ISSUE THREAD

**Issue by dereekb** [sibiraj-s/ngx-editor#337]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [X] Feature request
- [ ] Documentation issue or request

## Description
I noticed there wasn't a way to set the menu's dropdown direction, but the menu can be placed below the editor. It would be nice to have an input on the ngx-editor-menu element for changing the display direction of the menu popups.

My "workaround" right now is just:

```
.NgxEditor__Wrapper {

  .NgxEditor__Dropdown .NgxEditor__Dropdown--DropdownMenu,
  .NgxEditor__Popup {
    top: unset;
    bottom: calc(1.85rem + 2px);
  }
}
```

![Screen Shot 2021-04-21 at 5 07 40 AM](https://user-images.githubusercontent.com/3586580/115536622-9debc800-a25f-11eb-8bfc-bcb25f41d0b7.png)

**Comment by sibiraj-s** [comment]
Thanks for reporting this.

> It would be nice to have an input on the ngx-editor-menu element for changing the display direction of the menu popups.

Yeah. It is sensible option to have since the editor menu can be placed anywhere. 

For example. MenuComponent can accept an option like`dropdownPlacement` and value can be `top/bottom`

Please go with the workaround for few days. I am occupied here at work. I will try to fix it in coming weekend or the next. Meanwhile PR's are welcome.

**Comment by sibiraj-s** [comment]
Fixed in v9. Now you can set `dropdownPlacement` to `top` or `bottom`
