### ISSUE TITLE
[BUG]: Firefox - Text align justify

### ISSUE THREAD

**Issue by weblink-pd** [sibiraj-s/ngx-editor#350]
# I'm submitting a Bug report

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Text align justify doesn't work. 
When selecting the icon to justify text stays unchanged in editor.

### Version Information

```
ngx-editor: 10.0.0
angular: 12.0.3
```

### Browser

Mozilla Firefox - 89.0.1

**Comment by sibiraj-s** [comment]
This seems to be a Firefox bug, Firefox `text-align:justify` is not working with `white-space: pre-wrap` on its parent. See https://bugzilla.mozilla.org/show_bug.cgi?id=1253840. The editor uses Prosemirror under the hood, which needs `pre-wrap` to be set for functioning properly.

This is just for the editor. End users should see no issues though. Since the white-space property is just for the editor.

For now may be you can override the css property by

```css
.NgxEditor__Content {
 white-space: normal;
}
```

Mostly you should see no differences, there are very few edge cases but it is rare.

**Comment by sibiraj-s** [comment]
Since this is a browser issue, I am afraid it can't be fixed I guess. I am open to workarounds as long as it doesn't alter the DOM  structure.

**Comment by sibiraj-s** [comment]
The issue appears to be fixed now https://bugzilla.mozilla.org/show_bug.cgi?id=1253840.
