### ISSUE TITLE
If i am calling editor in for loop. Its not working. only the last editor in for loop working

### ISSUE THREAD

**Issue by priyank989** [sibiraj-s/ngx-editor#351]
if i am calling editor in for loop. Its not working. only the last editor in for loop working

```
<div *ngFor="let tests of test; let i = index"
             [ngClass]="'main-div-' + division.id">
        <div class="NgxEditor__Wrapper" [class.hidden]="!division.isEdit">
          <ngx-editor-menu [editor]="editor"> </ngx-editor-menu>
          <ngx-editor
          [editor]="editor"
          [ngModel]="html"
          [disabled]="false"
          [placeholder]="'test'">
          </ngx-editor>
        </div>
</div>
```

_Originally posted by @priyank989 in https://github.com/sibiraj-s/ngx-editor/issues/176#issuecomment-871905974_

**Comment by sibiraj-s** [comment]
Re-using the same editor is the issue here. I will see what I can do.

**Comment by priyank989** [comment]
@sibiraj-s okay thanks. i also know that i am using the same editor. Is there alternate you can provide.

Thanks

**Comment by priyank989** [comment]
@sibiraj-s 
have you find any solution for this

**Comment by sibiraj-s** [comment]
I couldn't find time to spare here. I will try this weekend. 

I am not sure on the use-case though. why do you have to loop the same editor? This will help me better approach the problem.

**Comment by priyank989** [comment]
@sibiraj-s i have implemented notebook. So in that notebook i have dynamic editor in for loop depend on condition.

**Comment by sibiraj-s** [comment]
Can you not create a new Editor for each condition? any reason for everything to be same (apart from simplicity)?

**Comment by priyank989** [comment]
@sibiraj-s Not possible because it is depend on condition.

**Comment by sibiraj-s** [comment]
Hi, @priyank989 A node is created when the editor is instantiated and listeners are attached to it. Since the DOM can't have duplicate nodes, thats the reason why you always end up in the last editor. 

I tried few tricks, but nothing seems to be working without breaking the existing setup, which I don't want to do. As things like the editor menu, floating menu, commands other custom implementations depends on this.

You will have to create a new editor for each one, similarly you would have created a model for each editor in the loop. No other options as of now.

I am open to implementation suggestions/PR.
