### ISSUE TITLE
[Bug]: bullet_list is not working

### ISSUE THREAD

**Issue by henafufa** [sibiraj-s/ngx-editor#465]
### What happened?

<img width="604" alt="Screen Shot 2023-04-20 at 9 08 52 AM" src="https://user-images.githubusercontent.com/37697829/233273390-4c5d6159-c584-46da-a8aa-a5ffac66bb54.png">

### Version

14.2.0

### Angular Version

14.3.0

### What browsers are you seeing the problem on?

Chrome

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Please provide some more information, Please verify if there is any css that overrides bullet list styles. 

It works perfectly fine for me. See https://ngx-editor.stackblitz.io//

**Comment by henafufa** [comment]
@sibiraj-s Thank you so much it seem my global css overrides it
Is there a way we can make ngx-editor-menu fixed to Ngx-editor while the content get scrolled? I will appreciate any help

**Comment by henafufa** [comment]
Dear Sibiraj
I responded there. thanks!
Thanks in advance
Sincerely,
Hena

**Comment by sibiraj-s** [comment]
Glad your issue is fixed.

Now, For making the content scrolled.

The editor content and editor menu are separate components. You should be be able to place wherever you like, it is not mandatory that you should keep them together. And, you can style it however you want, so to fix menu bar and scroll the content.

See some examples here, might give you some idea. https://sibiraj-s.github.io/ngx-editor/en/menu/

**Comment by henafufa** [comment]
Thank you for your support!
