### ISSUE TITLE
[Feature request]: Support Angular 16

### ISSUE THREAD

**Issue by IBlackI** [sibiraj-s/ngx-editor#475]
### Proposal

The current version of this package is for Angular version 14. Angular 16 has been released. 
Please create an updated version which has Angular 16 listed as a compatible version.

### Willing to submit a PR?

No

**Comment by TahaAttari** [comment]
the docs say Angular 14+ is supported, so should the package.json just be updated to allow all v14+ instead of ^14.1 like it is now?

**Comment by IBlackI** [comment]
Currently the [package.json](https://github.com/sibiraj-s/ngx-editor/blob/master/projects/ngx-editor/package.json#L17) specifies that version anything greater than or equals to 14.1.x but smaller than 15.x.x is supported. If version 15 and 16 are also supported the syntax would be `^14 || ^15 || ^16`. If version 14.0.x is not supported but 14.1.x is it would become `^14.1 || ^15 || ^16`. For more details [this cheatsheet provides a quick overview](https://devhints.io/semver).

The package.json does list the dependency on Angular [correctly as a peer dependency](https://angular.io/guide/creating-libraries#peer-dependencies).

**Comment by sibiraj-s** [comment]
Note. the package supports 14.1.0 or greater(including v16). The version between 14.0.0 and 14.1.0 is not supported due to a missing feature required by the editor to correctly implement dynamic components and was only added in v14.1 

Support for v16 is explicitly added via 4a9e7d0b10aadcd2f438ba2cad630c5c9460675b. Will be published soon.

Closing this as the support is already there. Let me know if there are issues. ngx-editor v16 will also be released soon.
