### ISSUE TITLE
[Feature request]: ol and ul does not support indent

### ISSUE THREAD

**Issue by DywiTom** [sibiraj-s/ngx-editor#547]
### Proposal

Hello!

See title.

Thanks!

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Yeah. it is by design. List items don't support indentation.  May be I can enabled decrease indent when inside a list item which removes the list.

Also, Please avoid `see title` description. Given a understandable title and explain in few words in the description, what's needed and any reasoning supporting it. Rather than to sound demanding.

Thank you.
