### ISSUE TITLE
[BUG] Including NgxEditorModule break AOT in Angular Universal

### ISSUE THREAD

**Issue by yharaskrik** [Sibiraj-S/ngx-editor#96]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

running
yarn add ngx-editor ngx-boostrap codemirror font-awesome
will cause angular to break when using AOT compiling. I am currently using NestJS which is a NodeJS based server that is serving the angular app with Universal. Running ng serve serves the angular site fine and causes no problems but with AOT the server just does not run.

### Version Information

```
ngx-editor: 3.3.0-rc.13
angular: 5.2.0
```

### Browser

- [ ] Chrome - x.x.x
- [x]  Mozilla Firefox - 59.0.2
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by Sibiraj-S** [comment]
@yharaskrik Can you post the error you get and if a minimal reproduction if available could be easier to solve things easier

**Comment by mrcomeback** [comment]
@Sibiraj-S hey dude, having same issue , if Angular Universal prerendering is deactivated everything work ok, but if active having this error:
An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: ReferenceError: navigator is not defined
at C:\WORK\Projects\clientapp\dist\main-server.js:1164:17
at userAgent (C:\WORK\Projects\clientapp\dist\main-server.js:1157:27)
at Object.module.exports (C:\WORK\Projects\clientapp\dist\main-server.js:1160:2)
at __webpack_require__ (C:\WORK\Projects\clientapp\dist\main-server.js:20:30)
at Object.freeze.canEnableToolbarOptions (C:\WORK\Projects\clientapp\dist\main-server.js:55427:151)
at Object.<anonymous> (C:\WORK\Projects\clientapp\dist\main-server.js:55430:2)
at __webpack_require__ (C:\WORK\Projects\clientapp\dist\main-server.js:20:30)
at Object.module.exports (C:\WORK\Projects\clientapp\dist\main-server.js:53232:70)
at __webpack_require__ (C:\WORK\Projects\clientapp\dist\main-server.js:20:30)
at Object.<anonymous> (C:\WORK\Projects\clientapp\dist\main-server.js:53163:77)
Current directory is: C:\WORK\Projects\

**Comment by denniskuligin** [comment]
Hm and I am using latest Angular CLI + universal, and getting the following weird error:
`ERROR in ./ngx-editor/ngx-editor.ngfactory.js
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-editor' in '/src/app'
ERROR in ./src/app/admin/dashboard/d-entry/d-entry-new/d-entry-new.component.ngfactory.js
Module not found: Error: Can't resolve 'ngx-editor' in '/src/app/admin/dashboard/d-entry/d-entry-new'
`

Let me know if you've any ideas how to workaround this. I am new to Universal, so maybe just noobish mistake (I'll look forward to resolution).

**Comment by denniskuligin** [comment]
And @mrcomeback , the problem with "navigator error" - relates to codemirror library

**Comment by Sibiraj-S** [comment]
Guys, i was little busy I will look at it tomorrow ASAP.

**Comment by yharaskrik** [comment]
No problem! My apologies for not getting back to you. I don't actually get an error, I'm using nestjs which compiles to a node express app and it fails silently on start, builds fine.

**Comment by denniskuligin** [comment]
@Sibiraj-S it's failing on default config of angular universal (angular 5+). As I mentioned before the problem with CodeMirror library exclusively.

**Comment by Sibiraj-S** [comment]
Hi everyone.

I never liked to have code-mirror anyway. I wanted to have a simple editor without any peerDependencies. 

I want to get rid of ngx-bootstrap, code-mirror and sooner or later font-awesome(I don't want user to cling to a particular icon set) too.

What do you guys think.

**Comment by mrcomeback** [comment]
@Sibiraj-S , this is good idea.
anyway a lot of people are using ngx-bootstrap and font-awesome , but "code mirror" i read first time in your documentation...
so will be much better without "CodeMirror".

**Comment by denniskuligin** [comment]
@Sibiraj-S it's a perfect decision, but I disagree about font-awesome.  Font-awesome won't be the real problem anyways, but "Codemirror" library is a real headache! 

By the way, if you'll succeed with that - you'll be the only one WYSIWYG editor working with out-of-box angular's universal.

**Comment by Sibiraj-S** [comment]
>  I disagree about font-awesome. 

I didn't plan to remove support font-awesome, just from peerDependency. I was just thinking of some strategy that would allow users to use any of icon needed which can be font-awesome or material or whatever they want. I guess I will end up something sooner.

**Comment by denniskuligin** [comment]
@Sibiraj-S listen I really believe, that you shouldn't waste any time to FA now. There are really more important things to do (CM, NGXB). 

By the way, mark your tasks as help needed where you want to get some help from the community. I will be happy to help =)

**Comment by Sibiraj-S** [comment]
@denniskuligin I am not doing it now. It is just an Idea.

>I will be happy to help

Thanks 🍻
